feat: ✨ 新增targets配置,用于修改构建产物的兼容性
umijs/father pull request #549
Opened 2022-11-24 06:46 UTC by huarse

2022-11-24 07:47 UTC, fz6m commented
babel 和 esbuild 接受的 targets 格式不一样，check 一下格式会不会更好。

2022-11-24 13:09 UTC, PeachScript requested changes
需要加一下用例，`tests/fixtures/build/targets`（umd/cjs/esm 正好对应 webpack/esbuild/babel）和 `tests/fixtures/build/bundless-swc-targets`（如果支持了的话）

2022-11-24 13:09 UTC, PeachScript commented on docs/config.md
> +指定源码编译产物的兼容性，目前仅支持 `babel` 和 `esbuild` 编译模式。以下是 `platform` 和 `transformer` 设置为不同值时传递的属性值示例
对用户最好一种配法，在 esbuild transformer 里做转换，类似：https://github.com/umijs/umi/blob/0507612e8176a512b772842d1640677eb839b3e7/packages/bundler-vite/src/config/transformer/target.ts#L15

2022-11-24 13:09 UTC, PeachScript commented on docs/config.md
> +| `browser`  | `swc`         | --                |
有空的话 swc 也可以加一下

2022-11-25 01:46 UTC, huarse commented on docs/config.md
> +| `browser`  | `swc`         | --                |
swc  已加

2022-11-25 02:44 UTC, huarse commented on src/builder/bundless/loaders/javascript/babel.ts
> +        typeof this.config.targets === 'object'
已经提取到统一的utils中处理

2022-11-25 02:46 UTC, huarse commented on docs/config.md
> +指定源码编译产物的兼容性，目前仅支持 `babel` 和 `esbuild` 编译模式。以下是 `platform` 和 `transformer` 设置为不同值时传递的属性值示例
这里主要是 babel, esbuild, swc  支持的数据类型几乎都不一样，尝试了一些方法都不太优雅

2022-11-25 02:48 UTC, huarse commented on docs/config.md
> +#### targets
同上一个问题，现在 bundle 用的是 babel，bundless 有3种编译方式，targets 还没有想到比较优雅的方式去统一

2022-11-25 05:23 UTC, huarse commented on docs/config.md
> +指定源码编译产物的兼容性，目前仅支持 `babel` 和 `esbuild` 编译模式。以下是 `platform` 和 `transformer` 设置为不同值时传递的属性值示例
在 util 里面加了一个统一处理层，针对不同类型输出不同数据格式

2022-11-25 05:23 UTC, huarse commented
> 需要加一下用例，`tests/fixtures/build/targets`（umd/cjs/esm 正好对应 webpack/esbuild/babel）和 `tests/fixtures/build/bundless-swc-targets`（如果支持了的话）

已添加

2022-11-25 05:28 UTC, huarse commented
> babel 和 esbuild 接受的 targets 格式不一样，check 一下格式会不会更好。

已统一为 `string | string[]`

2022-11-27 07:53 UTC, PeachScript commented on docs/config.md
> +> 2. `swc` 编译模式下仅支持语言版本，如 `es2017`, `es5` 等，不支持容器版本，且仅支持单个值，如果传入数组，则只取第一个；
看 SWC 文档也是支持浏览器的版本，是有什么不一样吗，https://swc.rs/docs/configuration/supported-browsers#targets

2022-11-27 07:53 UTC, PeachScript commented on docs/config.md
> +- 类型: `string` | `string[]`
最好能保持 `Record<string, string>` 的配法，和 Umi/dumi 保持一致，毕竟是同一个生态的

2022-11-28 01:43 UTC, huarse commented on docs/config.md
> +> 2. `swc` 编译模式下仅支持语言版本，如 `es2017`, `es5` 等，不支持容器版本，且仅支持单个值，如果传入数组，则只取第一个；
我试过传浏览器版本，会报错，看源码能发现支持的类型是：
```ts
export declare type JscTarget = "es3" | "es5" | "es2015" | "es2016" | "es2017" | "es2018" | "es2019" | "es2020" | "es2021" | "es2022";
```

2022-12-07 08:37 UTC, PeachScript commented on tests/fixtures/build/bundless-esbuild-targets/.fatherrc.ts
> +  targets: 'es6',
CI 挂了，应该是这里导致的，得改成 object 形式？

2022-12-07 08:40 UTC, PeachScript commented on tests/fixtures/build/bundless-esbuild-targets/.fatherrc.ts
> +    targets: { chrome: 45 },
试了下 45 会失败：

```bash
ERROR: Transforming async functions to the configured target environment ("chrome45") is not supported yet
```

2022-12-07 10:09 UTC, huarse commented on tests/fixtures/build/bundless-esbuild-targets/.fatherrc.ts
> +    targets: { chrome: 45 },
果然改成 54 就可以了

2022-12-07 12:59 UTC, PeachScript approved these changes

2022-12-07 13:00 UTC, merged